export const albumData = [
  {
    id: 1,
    albumName: 'Album 1',
    duration: '2:33',
    cover: '/big.jpg',
    music: 'musikaaa',
    artistName: 'saxeli ',
  },
  {
    id: 2,
    albumName: 'Album 2',
    duration: '3:45',
    cover: '/big.jpg',
    music: 'musikaaa',
    artistName: 'saxeli ',
  },
  {
    id: 3,
    albumName: 'Album 3',
    duration: '4:12',
    cover: '/big.jpg',
    music: 'musikaaa',
    artistName: 'saxeli ',
  },
  {
    id: 4,
    albumName: 'Album 4',
    duration: '5:01',
    cover: '/big.jpg',
    music: 'musikaaa',
    artistName: 'saxeli ',
  },
  {
    id: 5,
    albumName: 'Album 5',
    duration: '3:27',
    cover: '/big.jpg',
    music: 'musikaaa',
    artistName: 'saxeli ',
  },
  {
    id: 6,
    albumName: 'Album 6',
    duration: '2:54',
    cover: '/big.jpg',
    music: 'musikaaa',
    artistName: 'saxeli ',
  },
];
