export const PlayListData = [
  {
    src: '/2pac.jpg',
    musicName: 'Song 1',
    artistName: 'Artist 1',
    albumName: 'Album 1',
    createTime: '3:45',
  },
  {
    src: '/2pac.jpg',
    musicName: 'Song 2',
    artistName: 'Artist 2',
    albumName: 'Album 2',
    createTime: '4:12',
  },
  {
    src: '/2pac.jpg',
    musicName: 'Song 2',
    artistName: 'Artist 2',
    albumName: 'Album 2',
    createTime: '4:12',
  },
  {
    src: '/2pac.jpg',
    musicName: 'Song 2',
    artistName: 'Artist 2',
    albumName: 'Album 2',
    createTime: '4:12',
  },
  {
    src: '/2pac.jpg',
    musicName: 'Song 2',
    artistName: 'Artist 2',
    albumName: 'Album 2',
    createTime: '4:12',
  },
  {
    src: '/2pac.jpg',
    musicName: 'Song 2',
    artistName: 'Artist 2',
    albumName: 'Album 2',
    createTime: '4:12',
  },
  {
    src: '/2pac.jpg',
    musicName: 'Song 2',
    artistName: 'Artist 2',
    albumName: 'Album 2',
    createTime: '4:12',
  },
  {
    src: '/2pac.jpg',
    musicName: 'Song 2',
    artistName: 'Artist 2',
    albumName: 'Album 2',
    createTime: '4:12',
  },
  {
    src: '/2pac.jpg',
    musicName: 'Song 2',
    artistName: 'Artist 2',
    albumName: 'Album 2',
    createTime: '4:12',
  },
];
