export const artistSectionArray = [
  {
    id: 1,
    artistName: 'Kendriki',
    artistPhoto: '/kendrika.png',
    biography: 'zd zmebosad sand sasadjsabd sajd asd  dwasdsadi djsad',
    albums: [
      { id: 1, artistCover: '/big.jpg', albumName: 'Album Name 1' },
      { id: 2, artistCover: '/big.jpg', albumName: 'Album Name 2' },
      { id: 3, artistCover: '/big.jpg', albumName: 'Album Name 3' },
      { id: 4, artistCover: '/big.jpg', albumName: 'Album Name 4' },
    ],
    musics: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 1',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 2',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 3',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 6,
        duration: '3:33',
        albumName: 'Album Name 5',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 7,
        duration: '3:33',
        albumName: 'Album Name 6',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 8,
        duration: '3:33',
        albumName: 'Album Name 7',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 9,
        duration: '3:33',
        albumName: 'Album Name 8',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 10,
        duration: '3:33',
        albumName: 'Album Name 9',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 11,
        duration: '3:33',
        albumName: 'Album Name 10',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 12,
        duration: '3:33',
        albumName: 'Album Name 213',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 13,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 2,
    artistName: 'Kednriki',
    artistPhoto: '/kendrika.png',
    biography:
      'kendriki aris one of the best rappers in global of gldani so keep in mind bla blu bla ',
    albumData: [
      { id: 1, artistCover: '/big.jpg', albumName: 'Album Name 1' },
      { id: 2, artistCover: '/big.jpg', albumName: 'Album Name 2' },
      { id: 3, artistCover: '/big.jpg', albumName: 'Album Name 3' },
      { id: 4, artistCover: '/big.jpg', albumName: 'Album Name 4' },
    ],
    rowAlbumData: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 1',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 2',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 3',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 6,
        duration: '3:33',
        albumName: 'Album Name 5',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 7,
        duration: '3:33',
        albumName: 'Album Name 6',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 8,
        duration: '3:33',
        albumName: 'Album Name 7',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 9,
        duration: '3:33',
        albumName: 'Album Name 8',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 10,
        duration: '3:33',
        albumName: 'Album Name 9',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 11,
        duration: '3:33',
        albumName: 'Album Name 10',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 12,
        duration: '3:33',
        albumName: 'Album Name 213',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 13,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 3,
    artistName: 'Kendrik',
    artistPhoto: '/kendrika.png',
    biography:
      'ravaxar brat ager avashene me website da icodet ra vinaa number 1 aq visac unda gamevidessssssssssssss',
    albumData: [
      { id: 1, artistCover: '/big.jpg', albumName: 'Album Name 1' },
      { id: 2, artistCover: '/big.jpg', albumName: 'Album Name 2' },
      { id: 3, artistCover: '/big.jpg', albumName: 'Album Name 3' },
      { id: 4, artistCover: '/big.jpg', albumName: 'Album Name 4' },
    ],
    rowAlbumData: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 1',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 2',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 3',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 6,
        duration: '3:33',
        albumName: 'Album Name 5',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 7,
        duration: '3:33',
        albumName: 'Album Name 6',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 8,
        duration: '3:33',
        albumName: 'Album Name 7',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 9,
        duration: '3:33',
        albumName: 'Album Name 8',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 10,
        duration: '3:33',
        albumName: 'Album Name 9',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 11,
        duration: '3:33',
        albumName: 'Album Name 10',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 12,
        duration: '3:33',
        albumName: 'Album Name 213',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 13,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 4,
    artistName: 'didi',
    artistPhoto: '/big.jpg',
    biography: 'zd zmebo0000000000000000000',
    albumData: [
      { id: 1, artistCover: '/2pac.jpg', albumName: 'Album Name 1' },
      { id: 2, artistCover: '/big.jpg', albumName: 'Album Name 2' },
      { id: 3, artistCover: '/big.jpg', albumName: 'Album Name 3' },
      { id: 4, artistCover: '/big.jpg', albumName: 'Album Name 4' },
    ],
    rowAlbumData: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 1',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'zaodi',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 2',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 3',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 6,
        duration: '3:33',
        albumName: 'Album Name 5',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 7,
        duration: '3:33',
        albumName: 'Album Name 6',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 8,
        duration: '3:33',
        albumName: 'Album Name 7',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 9,
        duration: '3:33',
        albumName: 'Album Name 8',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 10,
        duration: '3:33',
        albumName: 'Album Name 9',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 11,
        duration: '3:33',
        albumName: 'Album Name 10',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 12,
        duration: '3:33',
        albumName: 'Album Name 213',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 13,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 5,
    artistPhoto: '/2pac.jpg',
    artistName: '2pac',
    biography: 'zd zmebo',
    albumData: [
      {
        id: 1,
        artistCover: '/big.jpg',
        albumName: 'Album Name 1',
      },
      {
        id: 2,
        artistCover: '/big.jpg',
        albumName: 'Album Name 2',
      },
      {
        id: 3,
        artistCover: '/big.jpg',
        albumName: 'Album Name 3',
      },
      {
        id: 4,
        artistCover: '/big.jpg',
        albumName: 'Album Name 4',
      },
    ],
    rowAlbumData: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 1',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 2',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 3',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 6,
        duration: '3:33',
        albumName: 'Album Name 5',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 7,
        duration: '3:33',
        albumName: 'Album Name 6',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 8,
        duration: '3:33',
        albumName: 'Album Name 7',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 9,
        duration: '3:33',
        albumName: 'Album Name 8',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 10,
        duration: '3:33',
        albumName: 'Album Name 9',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 11,
        duration: '3:33',
        albumName: 'Album Name 10',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 12,
        duration: '3:33',
        albumName: 'Album Name 213',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 13,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 6,
    artistPhoto: '/big.jpg',
    artistName: 'B.I.G',
    biography: 'zd zmebo',
    albumData: [
      { id: 1, artistCover: '/big.jpg', albumName: 'Album Name 1' },
      { id: 2, artistCover: '/big.jpg', albumName: 'Album Name 2' },
      { id: 3, artistCover: '/big.jpg', albumName: 'Album Name 3' },
      { id: 4, artistCover: '/big.jpg', albumName: 'Album Name 4' },
    ],
    rowAlbumData: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 1',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 2',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 3',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 6,
        duration: '3:33',
        albumName: 'Album Name 5',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 7,
        duration: '3:33',
        albumName: 'Album Name 6',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 8,
        duration: '3:33',
        albumName: 'Album Name 7',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 9,
        duration: '3:33',
        albumName: 'Album Name 8',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 10,
        duration: '3:33',
        albumName: 'Album Name 9',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 11,
        duration: '3:33',
        albumName: 'Album Name 10',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 12,
        duration: '3:33',
        albumName: 'Album Name 213',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 13,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 7,
    artistPhoto: '/2pac.jpg',
    artistName: '2pac',
    biography: 'zd zmebo',
    albumData: [
      { id: 1, artistCover: '/big.jpg', albumName: 'Album Name 1' },
      { id: 2, artistCover: '/big.jpg', albumName: 'Album Name 2' },
      { id: 3, artistCover: '/big.jpg', albumName: 'Album Name 3' },
      { id: 4, artistCover: '/big.jpg', albumName: 'Album Name 4' },
    ],
    rowAlbumData: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 1',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 2',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 3',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 6,
        duration: '3:33',
        albumName: 'Album Name 5',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 7,
        duration: '3:33',
        albumName: 'Album Name 6',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 8,
        duration: '3:33',
        albumName: 'Album Name 7',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 9,
        duration: '3:33',
        albumName: 'Album Name 8',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 10,
        duration: '3:33',
        albumName: 'Album Name 9',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 11,
        duration: '3:33',
        albumName: 'Album Name 10',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 12,
        duration: '3:33',
        albumName: 'Album Name 213',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 13,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 8,
    artistPhoto: '/big.jpg',
    artistName: 'B.I.G',
    biography: 'zd zmebo',
    albumData: [
      { id: 1, artistCover: '/big.jpg', albumName: 'Album Name 1' },
      { id: 2, artistCover: '/big.jpg', albumName: 'Album Name 2' },
      { id: 3, artistCover: '/big.jpg', albumName: 'Album Name 3' },
      { id: 4, artistCover: '/big.jpg', albumName: 'Album Name 4' },
    ],
    rowAlbumData: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 1',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 2',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 3',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 6,
        duration: '3:33',
        albumName: 'Album Name 5',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 7,
        duration: '3:33',
        albumName: 'Album Name 6',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 8,
        duration: '3:33',
        albumName: 'Album Name 7',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 9,
        duration: '3:33',
        albumName: 'Album Name 8',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 10,
        duration: '3:33',
        albumName: 'Album Name 9',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 11,
        duration: '3:33',
        albumName: 'Album Name 10',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 12,
        duration: '3:33',
        albumName: 'Album Name 213',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 13,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 9,
    artistPhoto: '/2pac.jpg',
    artistName: '2pac',
    biography:
      'zd zmebo ravaxart tuicit magdeni simoooooooooooooooon karoche aba tqven icit. ro gamoxvalt darket uechveli rac ar unda moxdes tqven gverdit var.',
    albumData: [
      { id: 1, artistCover: '/big.jpg', albumName: 'Album Name 1' },
      { id: 2, artistCover: '/big.jpg', albumName: 'Album Name 2' },
      { id: 3, artistCover: '/big.jpg', albumName: 'Album Name 3' },
      { id: 4, artistCover: '/big.jpg', albumName: 'Album Name 4' },
    ],
    rowAlbumData: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 1',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 2',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 3',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 6,
        duration: '3:33',
        albumName: 'Album Name 5',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 7,
        duration: '3:33',
        albumName: 'Album Name 6',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 8,
        duration: '3:33',
        albumName: 'Album Name 7',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 9,
        duration: '3:33',
        albumName: 'Album Name 8',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 10,
        duration: '3:33',
        albumName: 'Album Name 9',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 11,
        duration: '3:33',
        albumName: 'Album Name 10',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 12,
        duration: '3:33',
        albumName: 'Album Name 213',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 13,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
];
