export const AlbumCardDatas = [
  {
    albumName: 'Album Name 1',
    artistName: 'Artist Name 1',
    albumTime: '2018.05.03',
    songCount: '16 Songs',
    backgroundImage: '/zangi.png',
  },
  {
    albumName: 'Album Name 2',
    artistName: 'Artist Name 2',
    albumTime: '2018.05.03',
    songCount: '16 Songs',
    backgroundImage: '/gogo.png',
  },
  {
    albumName: 'Album Name 3',
    artistName: 'Artist Name 3',
    albumTime: '2018.05.03',
    songCount: '16 Songs',
    backgroundImage: '/kaci.png',
  },
  {
    albumName: 'Album Name 4',
    artistName: 'Artist Name 4',
    albumTime: '2018.05.03',
    songCount: '16 Songs',
    backgroundImage: '/zangi.png',
  },
  {
    albumName: 'Album Name 5',
    artistName: 'Artist Name 5',
    albumTime: '2018.05.03',
    songCount: '16 Songs',
    backgroundImage: '/gogo.png',
  },
  {
    albumName: 'Album Name 6',
    artistName: 'Artist Name 6',
    albumTime: '2018.05.03',
    songCount: '16 Songs',
    backgroundImage: '/kaci.png',
  },
  {
    albumName: 'Album Name 7',
    artistName: 'Artist Name 7',
    albumTime: '2018.05.03',
    songCount: '16 Songs',
    backgroundImage: '/zangi.png',
  },
  {
    albumName: 'Album Name 8',
    artistName: 'Artist Name 8',
    albumTime: '2018.05.03',
    songCount: '16 Songs',
    backgroundImage: '/gogo.png',
  },
  {
    albumName: 'Album Name 9',
    artistName: 'Artist Name 9',
    albumTime: '2018.05.03',
    songCount: '16 Songs',
    backgroundImage: '/kaci.png',
  },
];
