export const TopHitsAlbums = [
  {
    id: 1,
    duration: '3:33',
    albumName: 'Album Name 4123',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 2,
    duration: '3:33',
    albumName: 'Album Name 4123',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 3,
    duration: '3:33',
    albumName: 'Album Name 4123',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 4,
    duration: '3:33',
    albumName: 'Album Name 4123',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 5,
    duration: '3:33',
    albumName: 'Album Name 4123',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 6,
    duration: '3:33',
    albumName: 'Album Name 4123',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
];
