export const AlbumCardDatas = [
  {
    id: 1,
    albumName: 'Album Name 1',
    artistName: 'Artist Name 1',
    albumTime: '2018.05.03',
    songCount: 16,
    backgroundImage: '/zangi.png',
    albumHits: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 5,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 2,
    albumName: 'Album Name 2',
    artistName: 'Artist Name 2',
    albumTime: '2018.05.03',
    songCount: 16,
    backgroundImage: '/gogo.png',
    albumHits: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 5,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 6,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 7,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 8,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 9,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/big.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 10,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 3,
    albumName: 'Album Name 3',
    artistName: 'Artist Name 3',
    albumTime: '2018.05.03',
    songCount: 16,
    backgroundImage: '/kaci.png',
    albumHits: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 5,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 4,
    albumName: 'Album Name 4',
    artistName: 'Artist Name 4',
    albumTime: '2018.05.03',
    songCount: 16,
    backgroundImage: '/zangi.png',
    albumHits: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 5,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 5,
    albumName: 'Album Name 5',
    artistName: 'Artist Name 5',
    albumTime: '2018.05.03',
    songCount: 16,
    backgroundImage: '/gogo.png',
    albumHits: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 5,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 6,
    albumName: 'Album Name 6',
    artistName: 'Artist Name 6',
    albumTime: '2018.05.03',
    songCount: 16,
    backgroundImage: '/kaci.png',
    albumHits: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 5,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 7,
    albumName: 'Album Name 7',
    artistName: 'Artist Name 7',
    albumTime: '2018.05.03',
    songCount: 16,
    backgroundImage: '/zangi.png',
    albumHits: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 5,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 8,
    albumName: 'Album Name 8',
    artistName: 'Artist Name 8',
    albumTime: '2018.05.03',
    songCount: 16,
    backgroundImage: '/gogo.png',
    albumHits: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 5,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
  {
    id: 9,
    albumName: 'Album Name 9',
    artistName: 'Artist Name 9',
    albumTime: '2018.05.03',
    songCount: 16,
    backgroundImage: '/kaci.png',
    albumHits: [
      {
        id: 1,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 2,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 3,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 4,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
      {
        id: 5,
        duration: '3:33',
        albumName: 'Album Name 4123',
        cover: '/2pac.jpg',
        artistName: 'ArtistName',
        music: 'MusicName',
      },
    ],
  },
];
