export const rowAlbumData = [
  {
    id: 1,
    duration: '3:33',
    albumName: 'Album Name 1',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 2,
    duration: '3:33',
    albumName: 'Album Name 2',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 3,
    duration: '3:33',
    albumName: 'Album Name 3',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 4,
    duration: '3:33',
    albumName: 'Album Name 4',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 6,
    duration: '3:33',
    albumName: 'Album Name 5',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 7,
    duration: '3:33',
    albumName: 'Album Name 6',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 8,
    duration: '3:33',
    albumName: 'Album Name 7',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 9,
    duration: '3:33',
    albumName: 'Album Name 8',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 10,
    duration: '3:33',
    albumName: 'Album Name 9',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 11,
    duration: '3:33',
    albumName: 'Album Name 10',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 12,
    duration: '3:33',
    albumName: 'Album Name 213',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
  {
    id: 13,
    duration: '3:33',
    albumName: 'Album Name 4123',
    cover: '/big.jpg',
    artistName: 'ArtistName',
    music: 'MusicName',
  },
];
